### ISSUE TITLE
How did you come up with the steps?

### ISSUE THREAD

**Issue by yo1995** [unknownzerx/lguf-brightness#10]
Hi, 

Can I ask how did you come up with the steps for adjustment for both large and small steps? Does it have something to do with the manual?
Since I found them not continuous, I thought there might be some reasons for set it like that.
I'm trying to create a Windows version with GUI so your advice matters for me!

Thanks,

**Comment by ffffwh** [comment]
I've pushed a branch 'get_brightness'. Execute it on macOS, use brightness key to adjust brightness and record current brightness value.

**Comment by fd1012cd** [comment]
I've pushed a branch 'get_brightness'. Execute it on macOS, use brightness key to adjust brightness and record current brightness value.

**Comment by yo1995** [comment]
Thanks! I'll check it out later today 😄

**Comment by yo1995** [comment]
Thanks! I got exactly the same values with your `big_steps`.
Closed.
