### ISSUE TITLE
Doesn't work on Ultrafine 4K

### ISSUE THREAD

**Issue by primfins** [unknownzerx/lguf-brightness#4]
I have tested this program with my desktop PC on Windows 10.

The program runs like this:
Press '-' or '=' to adjust brightness.
Press '[' or: ']' to fine tune.
Press 'q' to quit.
Input:

When I try to adjust brightness by pressing '-', '=', '[', ']', it has no changes, Although it quits normally when I press 'q'. I thought that is a driver problem, so I updated the USB driver via Windows update and the program prints 'Failed to open the device...'

The VID and PID is 043E, 9A40.

**Comment by fd1012cd** [comment]
It might be the same as https://github.com/unknownzerx/lguf-brightness/issues/1

Try @ csujedihy 's work https://github.com/csujedihy/LG-Ultrafine-Brightness/releases
