### ISSUE TITLE
Failed to open the device (open_device failed)

### ISSUE THREAD

**Issue by ambroselittle** [unknownzerx/lguf-brightness#6]
Hi, when I run this, I get: "Failed to open the device (open_device failed)"

I check my USB Composite Devices. I have two.

#1:
USB\VID_0C76&PID_161E&REV_0100
USB\VID_0C76&PID_161E

#2:
USB\VID_046D&PID_085E&REV_0317
USB\VID_046D&PID_085E

This is plugged into the [ThunderboltEx card](https://www.asus.com/us/Motherboard-Accessory/ThunderboltEX-3/) on my [ASUS PRIME X299-DELUXE](https://www.asus.com/us/Motherboards/PRIME-X299-DELUXE/). The display is driven from their DisplayPort link. 

Any way to get this going?  Thanks in advance!

**Comment by fd1012cd** [comment]
The special USB device for adjusting brightness is not presenting, whose VID=043E, PID=9A40...

Have you connected the TB Header on the ThunderboltEx card to the mobo? Could the TB port used as a USB (2.0) port?

**Comment by ambroselittle** [comment]
I do have it connected to the header. I am not sure how to test/answer your question about USB 2. Sorry. Thanks for the help.

**Comment by csujedihy** [comment]
@ambroselittle, In some certain motherboard, you need to insert your ThunderboltEx card in the last slot (PCIE-4X?). Or you can't find your thunderbolt devices.

**Comment by ambroselittle** [comment]
@csujedihy, yup, it is. It is running my LG Ultrafine 5K fine, FWIW. I just can't change the settings. :)

**Comment by csujedihy** [comment]
As long as you find 0x43e, 0x9a40 device, you can use another tool listed below to adjust brightness.

https://github.com/csujedihy/LG-Ultrafine-Brightness

**Comment by ambroselittle** [comment]
So you got me thinking, and I searched around a bit and found that the mobo does not enable TB by default. I went into BIOS and set the following:

Enable Thunderbolt
- Set to the right port (PCI 4).
- Enable USB.
- Enable Boot.
- Set CPIe Cache-Line Size to 128 (I read somewhere that the Apple displays prefer this)

I saved and booted, and Windows saw the new devices. Now I can use the bulit in camera and speakers! Yay!  AND this tool works, too!  w00t. Thanks for the help, y'all!  Closing.

BTW, @csujedihy, I did try yours, and it said unable to set feature report and didn't change the brightness. FWIW.

**Comment by csujedihy** [comment]
@ambroselittle You should try plug in one more usb device on your monitor and see if your camera still works or not. On my monitor, if I plug in any usb device, the camera does not work.

**Comment by csujedihy** [comment]
It's weird and this tool lguf-brightness actually should work but not. We share basically same code but different API for USB. On my computer, lguf-brightness does not work but mine works fine. I can't figure out the reason.

@ambroselittle Are you running x64 Windows? My tool only works on x64.

**Comment by ambroselittle** [comment]
Yup. x64. 

Did your camera come back after unplugging the other thing?

**Comment by csujedihy** [comment]
After restart, it will come back.

**Comment by Hochiss** [comment]
> 
> As long as you find 0x43e, 0x9a40 device, you can use another tool listed below to adjust brightness.
> 
> https://github.com/csujedihy/LG-Ultrafine-Brightness

HID\VID_043E&PID_9A40 is HID Ambient Light Sensor as indicated by Wx, but cannot find correct driver.

would you @csujedihy mind sharing a built binary for Wx?
